server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git: https://github.com/victoralc/microservices/blob/main/
        native:
          search-paths: suppliers